#!/bin/bash
set -e

JSON_FILE=$1
HOST=${2:-localhost}
PORT=${3:-8081}

if [ $# -eq 0 ]; then
  echo "Please provide a bridge config json file";
  exit
fi

./scripts/wait_till_ready $HOST $PORT

echo "Posting bridge runtime config..."

curl -X PATCH $HOST:$PORT/runtime-config -H "Content-Type: application/json" -H "Accept: application/json" -H "server-auth-token: !changeme#" -d @$JSON_FILE