#!/bin/bash
# This script is used to run an e2e test in CI (see config.yml and cond_spot_run_tests).
# It sets a few environment variables used inside the docker-compose.yml, pulls images, and runs docker-compose.
set -e

export TEST=$1
export NUM_INNER_ROLLUP_TXS=${2:-3}
export NUM_OUTER_ROLLUP_PROOFS=${3:-2}
export VK=$4

if [ -n "$VK" ]; then
  export PROVERLESS=false
fi

if [ -n "$COMMIT_HASH" ]; then
  $(aws ecr get-login --region us-east-2 --no-include-email) 2> /dev/null

  for REPO in contracts halloumi kebab falafel sdk hummus end-to-end; do
    docker pull 278380418400.dkr.ecr.us-east-2.amazonaws.com/$REPO:cache-$COMMIT_HASH
    docker tag 278380418400.dkr.ecr.us-east-2.amazonaws.com/$REPO:cache-$COMMIT_HASH aztecprotocol/$REPO:latest
  done
fi

docker-compose rm -f

if [[ "$TEST" == *int_* ]] ; then
  docker-compose -f "docker-compose.integration.yml" up --exit-code-from end-to-end
elif [[ "$TEST" == *"browser"* ]]; then
  docker-compose -f "docker-compose-browser.yml" up --exit-code-from end-to-end
else
  docker-compose up --exit-code-from end-to-end
fi