#!/bin/bash
set -e

HOST=${1:-falafel}
PORT=${2:-8081}

./scripts/wait_for_port $HOST $PORT

echo "Waiting until $HOST:$PORT is ready..."
while [ "$(curl -s $HOST:$PORT | jq .isReady)" == "false" ]; do
    sleep 1
done