FROM aztecprotocol/clang:9.0.0
WORKDIR /usr/src/barretenberg
COPY . .
RUN mkdir build && cd build && cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ .. && MAKEFLAGS=-j8 cmake --build .
RUN cd build && ./test/barretenberg_tests
ENTRYPOINT /bin/bash