[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.20'
optimizer = true
optimizer_runs = 2000
allow_paths = [
    '../../contracts/'
]
remappings = [
    'core/=src/core/',
    'forge-std/=lib/forge-std/src',
    'rollup-encoder/=lib/rollup-encoder/src',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/', 
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    ]
fs_permissions = [
    {access = "read", path = 'verifier-fixtures/mock_rollup_proof_data_3x2.dat'},
    {access = "read", path = 'verifier-fixtures/rollup_proof_data_1x1.dat'},
    {access = "read", path = 'verifier-fixtures/encoded_rollup_proof_data_1x1.dat'}
]

[fmt]
variable_override_spacing=false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config