/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type { IBorrowerOperations, IBorrowerOperationsInterface } from '../IBorrowerOperations.js';

const _abi = [
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '_maxFee',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: '_collWithdrawal',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: '_debtChange',
        type: 'uint256',
      },
      {
        internalType: 'bool',
        name: 'isDebtIncrease',
        type: 'bool',
      },
      {
        internalType: 'address',
        name: '_upperHint',
        type: 'address',
      },
      {
        internalType: 'address',
        name: '_lowerHint',
        type: 'address',
      },
    ],
    name: 'adjustTrove',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'claimCollateral',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'closeTrove',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '_maxFee',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: '_LUSDAmount',
        type: 'uint256',
      },
      {
        internalType: 'address',
        name: '_upperHint',
        type: 'address',
      },
      {
        internalType: 'address',
        name: '_lowerHint',
        type: 'address',
      },
    ],
    name: 'openTrove',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '_amount',
        type: 'uint256',
      },
      {
        internalType: 'address',
        name: '_upperHint',
        type: 'address',
      },
      {
        internalType: 'address',
        name: '_lowerHint',
        type: 'address',
      },
    ],
    name: 'withdrawColl',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];

export class IBorrowerOperations__factory {
  static readonly abi = _abi;
  static createInterface(): IBorrowerOperationsInterface {
    return new utils.Interface(_abi) as IBorrowerOperationsInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IBorrowerOperations {
    return new Contract(address, _abi, signerOrProvider) as IBorrowerOperations;
  }
}
