/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type { ICurvePool, ICurvePoolInterface } from '../ICurvePool.js';

const _abi = [
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    name: 'coins',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'int128',
        name: 'i',
        type: 'int128',
      },
      {
        internalType: 'int128',
        name: 'j',
        type: 'int128',
      },
      {
        internalType: 'uint256',
        name: 'dx',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'min_dy',
        type: 'uint256',
      },
    ],
    name: 'exchange',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'int128',
        name: 'i',
        type: 'int128',
      },
      {
        internalType: 'int128',
        name: 'j',
        type: 'int128',
      },
      {
        internalType: 'uint256',
        name: 'dx',
        type: 'uint256',
      },
    ],
    name: 'get_dy',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];

export class ICurvePool__factory {
  static readonly abi = _abi;
  static createInterface(): ICurvePoolInterface {
    return new utils.Interface(_abi) as ICurvePoolInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ICurvePool {
    return new Contract(address, _abi, signerOrProvider) as ICurvePool;
  }
}
