/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type { IDeploymentValidator, IDeploymentValidatorInterface } from '../IDeploymentValidator.js';

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: 'wrappedPosition',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'pool',
        type: 'address',
      },
    ],
    name: 'checkPairValidation',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'pool',
        type: 'address',
      },
    ],
    name: 'checkPoolValidation',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'wrappedPosition',
        type: 'address',
      },
    ],
    name: 'checkWPValidation',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'wrappedPosition',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'pool',
        type: 'address',
      },
    ],
    name: 'validateAddresses',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'pool',
        type: 'address',
      },
    ],
    name: 'validatePoolAddress',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'wrappedPosition',
        type: 'address',
      },
    ],
    name: 'validateWPAddress',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];

export class IDeploymentValidator__factory {
  static readonly abi = _abi;
  static createInterface(): IDeploymentValidatorInterface {
    return new utils.Interface(_abi) as IDeploymentValidatorInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IDeploymentValidator {
    return new Contract(address, _abi, signerOrProvider) as IDeploymentValidator;
  }
}
