/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type { ILidoOracle, ILidoOracleInterface } from '../ILidoOracle.js';

const _abi = [
  {
    inputs: [],
    name: 'getLastCompletedReportDelta',
    outputs: [
      {
        internalType: 'uint256',
        name: 'postTotalPooledEther',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'preTotalPooledEther',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'timeElapsed',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];

export class ILidoOracle__factory {
  static readonly abi = _abi;
  static createInterface(): ILidoOracleInterface {
    return new utils.Interface(_abi) as ILidoOracleInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ILidoOracle {
    return new Contract(address, _abi, signerOrProvider) as ILidoOracle;
  }
}
