/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type { ILQTYStaking, ILQTYStakingInterface } from '../ILQTYStaking.js';

const _abi = [
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '_LQTYamount',
        type: 'uint256',
      },
    ],
    name: 'stake',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_user',
        type: 'address',
      },
    ],
    name: 'stakes',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '_LQTYamount',
        type: 'uint256',
      },
    ],
    name: 'unstake',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];

export class ILQTYStaking__factory {
  static readonly abi = _abi;
  static createInterface(): ILQTYStakingInterface {
    return new utils.Interface(_abi) as ILQTYStakingInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ILQTYStaking {
    return new Contract(address, _abi, signerOrProvider) as ILQTYStaking;
  }
}
