#!/bin/bash
set -e

TAG_POSTFIX=$1
TEST_PATTERN=$2

LAST_SUCCESSFUL_TESTED_COMMIT=$(last_successful_commit end-to-end $TAG_POSTFIX)

if check_rebuild "$LAST_SUCCESSFUL_TESTED_COMMIT" ../.rebuild_patterns; then
  ./spot_run_tests $CIRCLE_SHA1 $TEST_PATTERN
  tag_remote_image end-to-end cache-$CIRCLE_SHA1 cache-$CIRCLE_SHA1-$TAG_POSTFIX
fi