#!/bin/bash
set -e

IP=$1
COMMIT_HASH=$2
TEST=$3
SSH_CONFIG_PATH=${SSH_CONFIG_PATH:-../../.circleci/remote/ssh_config}

# Copy required files to spot instance.
scp -F $SSH_CONFIG_PATH ../docker-compose.yml $IP:.
scp -F $SSH_CONFIG_PATH ./run_tests $IP:.

# Run tests on remote instance.
ssh -F $SSH_CONFIG_PATH $IP ./run_tests $COMMIT_HASH $TEST