#!/bin/bash
set -e

COMMIT_HASH=$1
TEST=$2

# Get spot instance.
IP=$(request_spot $COMMIT_HASH:$TEST)

# Run tests remotely on spot instance, capturing success or failure.
set +e
./remote_run_tests $IP $COMMIT_HASH $TEST
CODE=$?

# Shutdown spot.
echo "Terminating spot instance..."
ssh -F $SSH_CONFIG_PATH $IP sudo halt -p > /dev/null 2>&1

exit $CODE