#!/bin/bash
set -e

# If rebuild is forced.
if [ "$REBUILD" == "true" ]; then
  echo "Forced rebuild requested."
  exit 0
fi

# If this is a tagged commit, rebuild.
if [ -n "$CIRCLE_TAG" ]; then
  echo "Rebuilding tagged commit."
  exit 0
fi

PATTERNS=${1:-.rebuild_patterns}

# If there are is no rebuild patterns file, create one from project directory.
if [ ! -f "$PATTERNS" ]; then
  echo "^$(git rev-parse --show-prefix)" > $PATTERNS
fi

if git diff --name-only ${LAST_SUCCESSFUL_COMMIT} ${CIRCLE_SHA1} | grep -q -f $PATTERNS; then
  exit 0
else
  exit 1
fi