#!/bin/bash
set -e

PATTERNS=${1:-.rebuild_patterns}

if [ ! -f "$PATTERNS" ]; then
  echo "^$(git rev-parse --show-prefix)" > $PATTERNS
fi

if git diff --name-only ${LAST_SUCCESSFUL_COMMIT} ${CIRCLE_SHA1} | grep -q -f $PATTERNS; then
  exit 0
else
  exit 1
fi