#!/bin/bash
# Conditionally runs a test script on a remote spot instance if any dependent code has changed between
# the last successfully run test and the present commit.
#
# It's expected to be run from the project directory, and that there be a directory called `scripts`
# with at minimum a script called `run_tests` to execute on the remote machine.
#
# Arguments are:
# 1. REPOSITORY: The project repository name in ECR.
# 2. NAME: A unique short name given to this test run. The remote image is tagged using this name to indicate success.
# 3... ARGS: Additional arguments to pass through.
set -e

REPOSITORY=$1
shift
NAME=$1

LAST_SUCCESSFUL_TESTED_COMMIT=$(last_successful_commit $REPOSITORY $NAME)

if check_rebuild $LAST_SUCCESSFUL_TESTED_COMMIT; then
  cd scripts
  spot_run_tests $@
  tag_remote_image $REPOSITORY cache-$COMMIT_HASH cache-$COMMIT_HASH-$NAME
fi