#!/bin/bash
# Conditionally runs a test script on a remote spot instance if any dependent code has changed between
# the last successfully run test and the present commit.
#
# It's expected to be run from the project directory, and that there be a directory called `scripts`
# with at minimum a script called `run_tests` to execute on the remote machine.
#
# Arguments are:
# 1. NAME: A unique short name given to this test run. The remote image is tagged using this name to indicate success.
# 2. RUN_SCRIPT: The name of the script to copy and run on the remote instance.
# 3. COMMIT_HASH: The commit hash that triggered this build. Used in image location and tagging.
# 4... ARGS: Additional arguments specific to RUN_SCRIPT.
set -e

REPOSITORY=$1
shift
NAME=$1

LAST_SUCCESSFUL_TESTED_COMMIT=$(last_successful_commit $REPOSITORY $NAME)

if check_rebuild $LAST_SUCCESSFUL_TESTED_COMMIT; then
  cd scripts
  spot_run_tests $@
  tag_remote_image $REPOSITORY cache-$COMMIT_HASH cache-$COMMIT_HASH-$NAME
fi