#!/bin/bash
set -e

REPOSITORY=$1
shift

# We're going to change dir away from project folder, so store path to rebuild patterns for check_rebuild script.
export REBUILD_PATTERNS=$PWD/.rebuild_patterns

cd ./scripts
cond_spot_run_script $REPOSITORY $JOB_NAME 32core ./run_tests $@