#!/bin/bash
set -e

REPOSITORY=$1
SERVICE=${2:-$REPOSITORY}
TF_DIR=$3

# Regardless of whether the repo changed or not, we want to tag image with this commit hash.
deploy_ecr $REPOSITORY

# Bail out if nothing changed.
IMAGE_COMMIT_TAG=cache-$CIRCLE_SHA1
image_exists $REPOSITORY $IMAGE_COMMIT_TAG || { echo "No new image found." && exit 0; }

deploy_terraform $TF_DIR
deploy_service $SERVICE