#!/bin/bash
set -e

REPOSITORY=$1

if [ ! -d ./terraform ]; then
   echo "No terraform found. Required for bucket and cloudfront outputs."
   exit 1
fi

extract_repo zk-money /usr/src/$REPOSITORY

if [ ! -d /usr/src/$REPOSITORY/dist ]; then
   echo "Expected dist folder at /usr/src/$REPOSITORY/dist"
   echo "Repository contents:"
   ls -al /usr/src/$REPOSITORY
   exit 1
fi

cd terraform
AWS_BUCKET_NAME=$(terraform output s3)
AWS_CLOUDFRONT_DISTRIBUTION=$(terraform output cloudfront)
cd ..

aws s3 rm s3://$AWS_BUCKET_NAME --recursive
aws s3 cp /usr/src/$REPOSITORY/dist s3://$AWS_BUCKET_NAME --recursive --metadata-directive REPLACE --cache-control "max-age=3600" --acl public-read
aws s3 cp \
       s3://$AWS_BUCKET_NAME \
       s3://$AWS_BUCKET_NAME \
       --exclude '*' \
       --include '*.js' \
       --no-guess-mime-type \
       --content-type="application/javascript; charset=utf-8" \
       --metadata-directive="REPLACE" \
       --recursive
aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION --paths "/*"
