#!/bin/bash
set -e

REPOSITORY=$1

# Regardless of whether the repo changed or not, we want to update tags in the deployment repo.
deploy_ecr $REPOSITORY

# Bail out if nothing changed.
LAST_SUCCESSFUL_COMMIT=$(last_successful_commit $REPOSITORY deployed)
echo "Last successfully deployed commit: $LAST_SUCCESSFUL_COMMIT"
if ! check_rebuild $LAST_SUCCESSFUL_COMMIT; then
  echo "No changes detected, skipping deployment."
  exit 0
fi

deploy_terraform $REPOSITORY

# If the project terraform maintains a service with the given name, restart it to run latest image.
deploy_service $DEPLOY_TAG-$REPOSITORY

# Tag the image as deployed.
tag_remote_image $REPOSITORY cache-$COMMIT_HASH cache-$COMMIT_HASH-deployed