#!/bin/bash
set -e

if [ -z "$COMMIT_TAG" ]; then
  echo "Can only push tagged builds to dockerhub."
  exit 1
fi

REPOSITORY=$1
IMAGE_COMMIT_URI=$ECR_URL/$REPOSITORY:$COMMIT_HASH
IMAGE_DEPLOY_URI=aztecprotocol/$REPOSITORY:$COMMIT_TAG

# Login.
ensure_repo $REPOSITORY $ECR_DEPLOY_REGION

# Pull image.
docker pull $IMAGE_COMMIT_URI

# Login to dockerhub.
docker login -u aztecprotocolci -p "${DOCKERHUB_PASSWORD}"

# Push image to dockerhub.
docker tag $IMAGE_COMMIT_URI $IMAGE_DEPLOY_URI
docker push $IMAGE_DEPLOY_URI