#!/bin/bash
set -e

# Redeploy service with latest image.
IMAGE=$1
SERVICE_NAME=${IMAGE%:*}
if aws ecs list-services --region $ECR_DEPLOY_REGION --cluster setup | grep "/$SERVICE_NAME\"" > /dev/null; then
  aws ecs update-service --region $ECR_DEPLOY_REGION --cluster setup --service $SERVICE_NAME --force-new-deployment
fi