#!/bin/bash
set -e

REPOSITORY=$1
IMAGE_COMMIT_URI=$ECR_URL/$REPOSITORY:cache-$COMMIT_HASH

# Login to build region and pull the build.
ensure_repo $REPOSITORY $ECR_REGION
docker pull $IMAGE_COMMIT_URI > /dev/null 2>&1

# Ensure ECR repository exists in deployment region.
ensure_repo $REPOSITORY $ECR_DEPLOY_REGION

# Push image to deployment repo with commit hash tag e.g:
# falafel:deadbeefcafebabe1337c0de
IMAGE_DEPLOY_COMMIT_URI=$ECR_DEPLOY_URL/$REPOSITORY:$COMMIT_HASH
docker tag $IMAGE_COMMIT_URI $IMAGE_DEPLOY_COMMIT_URI
docker push $IMAGE_DEPLOY_COMMIT_URI

# Image tag is project name, or commit tag if there is one.
IMAGE_TAG=${COMMIT_TAG:-$PROJECT}

IMAGE_DEPLOY_URI=$ECR_DEPLOY_URL/$REPOSITORY:$IMAGE_TAG
tag_remote_image $REPOSITORY $IMAGE_DEPLOY_COMMIT_URI $IMAGE_DEPLOY_URI $ECR_DEPLOY_REGION