#!/bin/bash
set -e

LIFECYCLE_POLICY='{
  "rules": [
    {
      "rulePriority": 1,
      "description": "No more than 20 cache images.",
      "selection": {
        "tagStatus": "tagged",
        "tagPrefixList": ["cache-"],
        "countType": "imageCountMoreThan",
        "countNumber": 20
      },
      "action": {
        "type": "expire"
      }
    }
  ]
}
'

REPOSITORY=$1
REGION=$2

$(aws ecr get-login --region $REGION --no-include-email) 2> /dev/null

# Create the repository if it doesn't exist.
if ! aws ecr describe-repositories --region $REGION --repository-names $REPOSITORY > /dev/null 2>&1; then
  echo "Creating repo: $REPOSITORY"
  aws ecr create-repository --region $REGION --repository-name $REPOSITORY
  aws ecr put-lifecycle-policy --region $REGION --repository-name $REPOSITORY --lifecycle-policy-text "$LIFECYCLE_POLICY"
elif changed .circleci/ensure_repo; then
  echo "Updating lifecycle rules for repo: $REPOSITORY"
  aws ecr put-lifecycle-policy --region $REGION --repository-name $REPOSITORY --lifecycle-policy-text "$LIFECYCLE_POLICY"
fi
echo