#!/bin/bash
# Given a repository, extracts the builds entire /usr/src dir to the given path.
set -e

REPOSITORY=$1
EXTRACT_PATH=${2:-./}
IMAGE_COMMIT_URI=$ECR_URL/$REPOSITORY:cache-$CIRCLE_SHA1
IMAGE_MASTER_URI=$ECR_URL/$REPOSITORY:master-$CIRCLE_SHA1

echo "Pulling $IMAGE_COMMIT_URI..."
if docker pull $IMAGE_COMMIT_URI > /dev/null 2>&1; then
  TEMP_CONTAINER=$(docker create $IMAGE_COMMIT_URI)
else
  echo "Pulling $IMAGE_MASTER_URI..."
  docker pull $IMAGE_MASTER_URI > /dev/null 2>&1
  TEMP_CONTAINER=$(docker create $IMAGE_MASTER_URI)
fi

echo "Created container $TEMP_CONTAINER"
echo "Extracting build for $REPOSITORY to $EXTRACT_PATH..."
docker cp $TEMP_CONTAINER:/usr/src $EXTRACT_PATH
docker rm -v $TEMP_CONTAINER > /dev/null