#!/bin/bash
# Given a repository, extracts the builds entire /usr/src dir to the given path.
set -e

REPOSITORY=$1
EXTRACT_FROM=${2:-/usr/src}
EXTRACT_TO=${3:-./}
IMAGE_COMMIT_URI=$ECR_URL/$REPOSITORY:cache-$CIRCLE_SHA1
IMAGE_MASTER_URI=$ECR_URL/$REPOSITORY:master-$CIRCLE_SHA1

echo "Pulling $IMAGE_COMMIT_URI..."
if docker pull $IMAGE_COMMIT_URI > /dev/null 2>&1; then
  TEMP_CONTAINER=$(docker create $IMAGE_COMMIT_URI)
else
  echo "Pulling $IMAGE_MASTER_URI..."
  docker pull $IMAGE_MASTER_URI > /dev/null 2>&1
  TEMP_CONTAINER=$(docker create $IMAGE_MASTER_URI)
fi

echo "Extracting $EXTRACT_FROM from $REPOSITORY to $EXTRACT_TO..."
docker cp $TEMP_CONTAINER:$EXTRACT_FROM $EXTRACT_TO
docker rm -v $TEMP_CONTAINER > /dev/null