#!/bin/bash
# For a given repository, init any required submodules.
set -euo pipefail

REPOSITORY=$1

BUILD_DIR=$(query_manifest buildDir $REPOSITORY)
if [ -d "$BUILD_DIR" ]; then
  echo "Initialising any submodules under $REPOSITORY buildDir: $BUILD_DIR"
  git submodule update --init --recursive $BUILD_DIR && exit || echo "No submodules under buildDir"
fi

SUBMODULE_PATH=$(query_manifest submodulePath $REPOSITORY)
if [ -n "$SUBMODULE_PATH" ]; then
  # TODO: Needs to actually init all dependency submodules as well.
  echo "Initialising submodule: $SUBMODULE_PATH"
  git submodule update --init --recursive $SUBMODULE_PATH
fi