#!/bin/bash

# Find the last successful commit on this branch that deployed successfully.
LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH?filter=successful&limit=100"
LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '[.[] | select(.build_parameters.CIRCLE_JOB == "deploy")][0].vcs_revision'`
OFFSET=0
while [ "$LAST_SUCCESSFUL_COMMIT" == "null" ]; do
  OFFSET=$[OFFSET+100]
  if [ "$OFFSET" -gt "1000" ]; then
    >&2 echo "Failed to find last successful deployment commit. Perhaps it was too long ago? Find better solution."
    exit 0
  fi
  LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH?filter=successful&limit=100&offset=$OFFSET"
  LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '[.[] | select(.build_parameters.CIRCLE_JOB == "deploy")][0].vcs_revision'`
done

echo $LAST_SUCCESSFUL_COMMIT