#!/bin/bash

REPOSITORY=$1

if [ -n "$2" ]; then
  TAG_POSTFIX=-$2
fi

# We are assuming that there has been a successful build of the given repo
# within the last 50 commits. If not return nothing.
for COMMIT_HASH in $(git log -n 50 --pretty=format:"%H"); do
  if image_exists $REPOSITORY cache-${COMMIT_HASH}$TAG_POSTFIX; then
    echo $COMMIT_HASH
    exit 0
  fi
done