#!/bin/bash
set -e

IP=$1
shift
SSH_CONFIG_PATH=${SSH_CONFIG_PATH:-$BUILD_SYSTEM_PATH/remote/ssh_config}

# Copy all files in current working directory to spot instance.
# It's expected there be a file matching SCRIPT to execute on the remote machine.
scp -F $SSH_CONFIG_PATH ./* $IP:.

# Run script on remote instance.
ssh -A -F $SSH_CONFIG_PATH $IP "COMMIT_HASH=$COMMIT_HASH COMMIT_BRANCH=$COMMIT_BRANCH COMMIT_TAG=$COMMIT_TAG JOB_NAME=$JOB_NAME GIT_REPOSITORY_URL=$GIT_REPOSITORY_URL DOCKERHUB_PASSWORD=$DOCKERHUB_PASSWORD $@"