#!/bin/bash
[ -n "$CIRCLE_TOKEN" ] || (echo "No CIRCLE_TOKEN available." && exit 1)

if [ "$CIRCLE_BRANCH" == "master" ]; then
  LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/master?filter=successful&limit=100"
  LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '[.[] | select(.build_parameters.CIRCLE_JOB == "deploy")][0].vcs_revision'`
  OFFSET=0
  while [ "$LAST_SUCCESSFUL_COMMIT" == "null" ]; do
    OFFSET=$[OFFSET+100]
    if [ "$OFFSET" -gt "1000" ]; then
      echo "Failed to find last successful commit. Perhaps it was too long ago? Find better solution."
      exit 1
    fi
    LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/master?filter=successful&limit=100&offset=$OFFSET"
    LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '[.[] | select(.build_parameters.CIRCLE_JOB == "deploy")][0].vcs_revision'`
  done
  echo export LAST_SUCCESSFUL_COMMIT=$LAST_SUCCESSFUL_COMMIT >> $BASH_ENV
else
  # CircleCI checkout mangles master for some reason. Reset it.
  git branch -f master origin/master
  echo export LAST_SUCCESSFUL_COMMIT=`git merge-base master $CIRCLE_BRANCH` >> $BASH_ENV
fi

echo export PATH=$PATH:$(pwd)/.circleci >> $BASH_ENV
echo export AWS_DEFAULT_REGION=eu-west-2 >> $BASH_ENV
echo export ECR_REGION=us-east-2 >> $BASH_ENV
echo export ECR_URL=278380418400.dkr.ecr.us-east-2.amazonaws.com >> $BASH_ENV
echo export ECR_DEPLOY_REGION=eu-west-2 >> $BASH_ENV
echo export ECR_DEPLOY_URL=278380418400.dkr.ecr.eu-west-2.amazonaws.com >> $BASH_ENV
echo export REBUILD=$1 >> $BASH_ENV
echo export TF_VAR_IMAGE_TAG=$CIRCLE_TAG >> $BASH_ENV
cat $BASH_ENV
