#!/bin/bash
[ -n "$CIRCLE_TOKEN" ] || (echo "No CIRCLE_TOKEN available." && exit 1)

if [ "$CIRCLE_BRANCH" == "master" ]; then
  # Find the last successful commit. This is the last master that deployed successfully.
  LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/master?filter=successful&limit=100"
  LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '[.[] | select(.build_parameters.CIRCLE_JOB == "deploy")][0].vcs_revision'`
  OFFSET=0
  while [ "$LAST_SUCCESSFUL_COMMIT" == "null" ]; do
    OFFSET=$[OFFSET+100]
    if [ "$OFFSET" -gt "1000" ]; then
      echo "Failed to find last successful commit. Perhaps it was too long ago? Find better solution."
      exit 1
    fi
    LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/master?filter=successful&limit=100&offset=$OFFSET"
    LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '[.[] | select(.build_parameters.CIRCLE_JOB == "deploy")][0].vcs_revision'`
  done
else
  # CircleCI checkout mangles master for some reason. Reset it.
  git branch -f master origin/master

  if [ -n "$CIRCLE_TAG" ]; then
    # CIRCLE_BRANCH is not set for tagged builds. The branch name should match the tag without the patch version.
    CIRCLE_BRANCH=$(echo $CIRCLE_TAG | grep -oP 'v\d+.\d+')
    git fetch
  fi

  # The last successful commit is the commit at which we forked off master.
  LAST_SUCCESSFUL_COMMIT=`git merge-base master $CIRCLE_BRANCH`
fi

[ -n "$LAST_SUCCESSFUL_COMMIT" ] || { echo "Unable to determine the last successful commit." && exit 1; }

echo export PATH=$PATH:$(pwd)/.circleci >> $BASH_ENV
echo export AWS_DEFAULT_REGION=eu-west-2 >> $BASH_ENV
echo export ECR_REGION=us-east-2 >> $BASH_ENV
echo export ECR_URL=278380418400.dkr.ecr.us-east-2.amazonaws.com >> $BASH_ENV
echo export ECR_DEPLOY_REGION=eu-west-2 >> $BASH_ENV
echo export ECR_DEPLOY_URL=278380418400.dkr.ecr.eu-west-2.amazonaws.com >> $BASH_ENV
echo export REBUILD=$1 >> $BASH_ENV
echo export TF_VAR_IMAGE_TAG=$CIRCLE_TAG >> $BASH_ENV
echo export CIRCLE_BRANCH=$CIRCLE_BRANCH >> $BASH_ENV
echo export LAST_SUCCESSFUL_COMMIT=$LAST_SUCCESSFUL_COMMIT >> $BASH_ENV
cat $BASH_ENV
