#!/bin/bash
# Runs a test script on a remote spot instance. Arguments are:
# 1. NAME: A unique short name given to this test run. The spot instance is tagged with this name.
# 2... ARGS: Additional arguments to pass through.
set -e

NAME=$1

# Get spot instance.
IP=$(request_spot $COMMIT_HASH:$NAME)

# Run tests remotely on spot instance, capturing success or failure.
set +e
remote_run_tests $IP $@
CODE=$?

# Shutdown spot.
echo "Terminating spot instance..."
ssh -F $SSH_CONFIG_PATH $IP sudo halt -p > /dev/null 2>&1

exit $CODE