#!/bin/sh
set -e

if [ -z "$ROLLUP_CONTRACT_ADDRESS" ]; 
then
RESULT=$(curl $ETHEREUM_HOST)

ROLLUP_CONTRACT_ADDRESS_VALUE=$(echo $RESULT | jq -r '.redeployConfig.rollupContractAddress')
PERMIT_HELPER_ADDRESS_VALUE=$(echo $RESULT | jq -r '.redeployConfig.permitHelperAddress')
PRICE_FEED_CONTRACT_ADDRESSES_VALUE=$(echo $RESULT | jq -r '.redeployConfig.priceFeedContractAddresses')

echo "ROLLUP_CONTRACT_ADDRESS=$ROLLUP_CONTRACT_ADDRESS_VALUE"
echo "PERMIT_HELPER_CONTRACT_ADDRESS=$PERMIT_HELPER_ADDRESS_VALUE"
echo "PRICE_FEED_CONTRACT_ADDRESSES=$PRICE_FEED_CONTRACT_ADDRESSES_VALUE"

export ROLLUP_CONTRACT_ADDRESS=$ROLLUP_CONTRACT_ADDRESS_VALUE
export PERMIT_HELPER_CONTRACT_ADDRESS=$PERMIT_HELPER_ADDRESS_VALUE
export PRICE_FEED_CONTRACT_ADDRESSES=$PRICE_FEED_CONTRACT_ADDRESSES_VALUE
fi