packageExtensions:
  '@walletconnect/iso-crypto@*':
    dependencies:
      '@walletconnect/encoding': '*'
  '@web3-react/core@*':
    dependencies:
      '@ethersproject/bytes': '*'
  react-router-dom@*:
    dependencies:
      '@remix-run/router': '*'
  chalk@5.0.1:
    dependencies:
      '#ansi-styles': npm:ansi-styles@6.1.0
      '#supports-color': npm:supports-color@9.2.2
  json-normalize@*:
    dependencies:
      'source-map-support': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.3.cjs
