/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from '../common.js';

export declare namespace IPoolManager {
  export type StrategyParamsStruct = {
    lastReport: PromiseOrValue<BigNumberish>;
    totalStrategyDebt: PromiseOrValue<BigNumberish>;
    debtRatio: PromiseOrValue<BigNumberish>;
  };

  export type StrategyParamsStructOutput = [BigNumber, BigNumber, BigNumber] & {
    lastReport: BigNumber;
    totalStrategyDebt: BigNumber;
    debtRatio: BigNumber;
  };
}

export interface IPoolManagerInterface extends utils.Interface {
  functions: {
    'strategies(address)': FunctionFragment;
    'strategyList(uint256)': FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: 'strategies' | 'strategyList'): FunctionFragment;

  encodeFunctionData(functionFragment: 'strategies', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(functionFragment: 'strategyList', values: [PromiseOrValue<BigNumberish>]): string;

  decodeFunctionResult(functionFragment: 'strategies', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'strategyList', data: BytesLike): Result;

  events: {};
}

export interface IPoolManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPoolManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    strategies(
      _strategy: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[IPoolManager.StrategyParamsStructOutput]>;

    strategyList(arg0: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<[string]>;
  };

  strategies(
    _strategy: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<IPoolManager.StrategyParamsStructOutput>;

  strategyList(arg0: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    strategies(
      _strategy: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<IPoolManager.StrategyParamsStructOutput>;

    strategyList(arg0: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    strategies(_strategy: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    strategyList(arg0: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    strategies(_strategy: PromiseOrValue<string>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    strategyList(arg0: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
