/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from './common.js';

export interface IBorrowerOperationsInterface extends utils.Interface {
  functions: {
    'adjustTrove(uint256,uint256,uint256,bool,address,address)': FunctionFragment;
    'claimCollateral()': FunctionFragment;
    'closeTrove()': FunctionFragment;
    'openTrove(uint256,uint256,address,address)': FunctionFragment;
    'withdrawColl(uint256,address,address)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: 'adjustTrove' | 'claimCollateral' | 'closeTrove' | 'openTrove' | 'withdrawColl',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'adjustTrove',
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
    ],
  ): string;
  encodeFunctionData(functionFragment: 'claimCollateral', values?: undefined): string;
  encodeFunctionData(functionFragment: 'closeTrove', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'openTrove',
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: 'withdrawColl',
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>, PromiseOrValue<string>],
  ): string;

  decodeFunctionResult(functionFragment: 'adjustTrove', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'claimCollateral', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'closeTrove', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'openTrove', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'withdrawColl', data: BytesLike): Result;

  events: {};
}

export interface IBorrowerOperations extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IBorrowerOperationsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    adjustTrove(
      _maxFee: PromiseOrValue<BigNumberish>,
      _collWithdrawal: PromiseOrValue<BigNumberish>,
      _debtChange: PromiseOrValue<BigNumberish>,
      isDebtIncrease: PromiseOrValue<boolean>,
      _upperHint: PromiseOrValue<string>,
      _lowerHint: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    claimCollateral(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>;

    closeTrove(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>;

    openTrove(
      _maxFee: PromiseOrValue<BigNumberish>,
      _LUSDAmount: PromiseOrValue<BigNumberish>,
      _upperHint: PromiseOrValue<string>,
      _lowerHint: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    withdrawColl(
      _amount: PromiseOrValue<BigNumberish>,
      _upperHint: PromiseOrValue<string>,
      _lowerHint: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;
  };

  adjustTrove(
    _maxFee: PromiseOrValue<BigNumberish>,
    _collWithdrawal: PromiseOrValue<BigNumberish>,
    _debtChange: PromiseOrValue<BigNumberish>,
    isDebtIncrease: PromiseOrValue<boolean>,
    _upperHint: PromiseOrValue<string>,
    _lowerHint: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  claimCollateral(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>;

  closeTrove(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>;

  openTrove(
    _maxFee: PromiseOrValue<BigNumberish>,
    _LUSDAmount: PromiseOrValue<BigNumberish>,
    _upperHint: PromiseOrValue<string>,
    _lowerHint: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  withdrawColl(
    _amount: PromiseOrValue<BigNumberish>,
    _upperHint: PromiseOrValue<string>,
    _lowerHint: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  callStatic: {
    adjustTrove(
      _maxFee: PromiseOrValue<BigNumberish>,
      _collWithdrawal: PromiseOrValue<BigNumberish>,
      _debtChange: PromiseOrValue<BigNumberish>,
      isDebtIncrease: PromiseOrValue<boolean>,
      _upperHint: PromiseOrValue<string>,
      _lowerHint: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;

    claimCollateral(overrides?: CallOverrides): Promise<void>;

    closeTrove(overrides?: CallOverrides): Promise<void>;

    openTrove(
      _maxFee: PromiseOrValue<BigNumberish>,
      _LUSDAmount: PromiseOrValue<BigNumberish>,
      _upperHint: PromiseOrValue<string>,
      _lowerHint: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;

    withdrawColl(
      _amount: PromiseOrValue<BigNumberish>,
      _upperHint: PromiseOrValue<string>,
      _lowerHint: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    adjustTrove(
      _maxFee: PromiseOrValue<BigNumberish>,
      _collWithdrawal: PromiseOrValue<BigNumberish>,
      _debtChange: PromiseOrValue<BigNumberish>,
      isDebtIncrease: PromiseOrValue<boolean>,
      _upperHint: PromiseOrValue<string>,
      _lowerHint: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    claimCollateral(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<BigNumber>;

    closeTrove(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<BigNumber>;

    openTrove(
      _maxFee: PromiseOrValue<BigNumberish>,
      _LUSDAmount: PromiseOrValue<BigNumberish>,
      _upperHint: PromiseOrValue<string>,
      _lowerHint: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    withdrawColl(
      _amount: PromiseOrValue<BigNumberish>,
      _upperHint: PromiseOrValue<string>,
      _lowerHint: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    adjustTrove(
      _maxFee: PromiseOrValue<BigNumberish>,
      _collWithdrawal: PromiseOrValue<BigNumberish>,
      _debtChange: PromiseOrValue<BigNumberish>,
      isDebtIncrease: PromiseOrValue<boolean>,
      _upperHint: PromiseOrValue<string>,
      _lowerHint: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    claimCollateral(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<PopulatedTransaction>;

    closeTrove(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<PopulatedTransaction>;

    openTrove(
      _maxFee: PromiseOrValue<BigNumberish>,
      _LUSDAmount: PromiseOrValue<BigNumberish>,
      _upperHint: PromiseOrValue<string>,
      _lowerHint: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    withdrawColl(
      _amount: PromiseOrValue<BigNumberish>,
      _upperHint: PromiseOrValue<string>,
      _lowerHint: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;
  };
}
