/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from './common.js';

export declare namespace ISubsidy {
  export type SubsidyStruct = {
    available: PromiseOrValue<BigNumberish>;
    gasUsage: PromiseOrValue<BigNumberish>;
    minGasPerMinute: PromiseOrValue<BigNumberish>;
    gasPerMinute: PromiseOrValue<BigNumberish>;
    lastUpdated: PromiseOrValue<BigNumberish>;
  };

  export type SubsidyStructOutput = [BigNumber, number, number, number, number] & {
    available: BigNumber;
    gasUsage: number;
    minGasPerMinute: number;
    gasPerMinute: number;
    lastUpdated: number;
  };
}

export interface ISubsidyInterface extends utils.Interface {
  functions: {
    'MIN_SUBSIDY_VALUE()': FunctionFragment;
    'claimSubsidy(uint256,address)': FunctionFragment;
    'claimableAmount(address)': FunctionFragment;
    'getAccumulatedSubsidyAmount(address,uint256)': FunctionFragment;
    'getSubsidy(address,uint256)': FunctionFragment;
    'isRegistered(address)': FunctionFragment;
    'registerBeneficiary(address)': FunctionFragment;
    'setGasUsageAndMinGasPerMinute(uint256,uint32,uint32)': FunctionFragment;
    'setGasUsageAndMinGasPerMinute(uint256[],uint32[],uint32[])': FunctionFragment;
    'subsidize(address,uint256,uint32)': FunctionFragment;
    'topUp(address,uint256)': FunctionFragment;
    'withdraw(address)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | 'MIN_SUBSIDY_VALUE'
      | 'claimSubsidy'
      | 'claimableAmount'
      | 'getAccumulatedSubsidyAmount'
      | 'getSubsidy'
      | 'isRegistered'
      | 'registerBeneficiary'
      | 'setGasUsageAndMinGasPerMinute(uint256,uint32,uint32)'
      | 'setGasUsageAndMinGasPerMinute(uint256[],uint32[],uint32[])'
      | 'subsidize'
      | 'topUp'
      | 'withdraw',
  ): FunctionFragment;

  encodeFunctionData(functionFragment: 'MIN_SUBSIDY_VALUE', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'claimSubsidy',
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>],
  ): string;
  encodeFunctionData(functionFragment: 'claimableAmount', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(
    functionFragment: 'getAccumulatedSubsidyAmount',
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: 'getSubsidy',
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(functionFragment: 'isRegistered', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(functionFragment: 'registerBeneficiary', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(
    functionFragment: 'setGasUsageAndMinGasPerMinute(uint256,uint32,uint32)',
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: 'setGasUsageAndMinGasPerMinute(uint256[],uint32[],uint32[])',
    values: [PromiseOrValue<BigNumberish>[], PromiseOrValue<BigNumberish>[], PromiseOrValue<BigNumberish>[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'subsidize',
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(functionFragment: 'topUp', values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: 'withdraw', values: [PromiseOrValue<string>]): string;

  decodeFunctionResult(functionFragment: 'MIN_SUBSIDY_VALUE', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'claimSubsidy', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'claimableAmount', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getAccumulatedSubsidyAmount', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getSubsidy', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'isRegistered', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'registerBeneficiary', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'setGasUsageAndMinGasPerMinute(uint256,uint32,uint32)',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setGasUsageAndMinGasPerMinute(uint256[],uint32[],uint32[])',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'subsidize', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'topUp', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;

  events: {};
}

export interface ISubsidy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ISubsidyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MIN_SUBSIDY_VALUE(overrides?: CallOverrides): Promise<[BigNumber]>;

    claimSubsidy(
      _criteria: PromiseOrValue<BigNumberish>,
      _beneficiary: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    claimableAmount(_beneficiary: PromiseOrValue<string>, overrides?: CallOverrides): Promise<[BigNumber]>;

    getAccumulatedSubsidyAmount(
      _bridge: PromiseOrValue<string>,
      _criteria: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    getSubsidy(
      _bridge: PromiseOrValue<string>,
      _criteria: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<[ISubsidy.SubsidyStructOutput]>;

    isRegistered(_beneficiary: PromiseOrValue<string>, overrides?: CallOverrides): Promise<[boolean]>;

    registerBeneficiary(
      _beneficiary: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    'setGasUsageAndMinGasPerMinute(uint256,uint32,uint32)'(
      _criteria: PromiseOrValue<BigNumberish>,
      _gasUsage: PromiseOrValue<BigNumberish>,
      _minGasPerMinute: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    'setGasUsageAndMinGasPerMinute(uint256[],uint32[],uint32[])'(
      _criteria: PromiseOrValue<BigNumberish>[],
      _gasUsage: PromiseOrValue<BigNumberish>[],
      _minGasPerMinute: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    subsidize(
      _bridge: PromiseOrValue<string>,
      _criteria: PromiseOrValue<BigNumberish>,
      _gasPerMinute: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    topUp(
      _bridge: PromiseOrValue<string>,
      _criteria: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    withdraw(
      _beneficiary: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;
  };

  MIN_SUBSIDY_VALUE(overrides?: CallOverrides): Promise<BigNumber>;

  claimSubsidy(
    _criteria: PromiseOrValue<BigNumberish>,
    _beneficiary: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  claimableAmount(_beneficiary: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

  getAccumulatedSubsidyAmount(
    _bridge: PromiseOrValue<string>,
    _criteria: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  getSubsidy(
    _bridge: PromiseOrValue<string>,
    _criteria: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides,
  ): Promise<ISubsidy.SubsidyStructOutput>;

  isRegistered(_beneficiary: PromiseOrValue<string>, overrides?: CallOverrides): Promise<boolean>;

  registerBeneficiary(
    _beneficiary: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  'setGasUsageAndMinGasPerMinute(uint256,uint32,uint32)'(
    _criteria: PromiseOrValue<BigNumberish>,
    _gasUsage: PromiseOrValue<BigNumberish>,
    _minGasPerMinute: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  'setGasUsageAndMinGasPerMinute(uint256[],uint32[],uint32[])'(
    _criteria: PromiseOrValue<BigNumberish>[],
    _gasUsage: PromiseOrValue<BigNumberish>[],
    _minGasPerMinute: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  subsidize(
    _bridge: PromiseOrValue<string>,
    _criteria: PromiseOrValue<BigNumberish>,
    _gasPerMinute: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  topUp(
    _bridge: PromiseOrValue<string>,
    _criteria: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  withdraw(
    _beneficiary: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  callStatic: {
    MIN_SUBSIDY_VALUE(overrides?: CallOverrides): Promise<BigNumber>;

    claimSubsidy(
      _criteria: PromiseOrValue<BigNumberish>,
      _beneficiary: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    claimableAmount(_beneficiary: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    getAccumulatedSubsidyAmount(
      _bridge: PromiseOrValue<string>,
      _criteria: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    getSubsidy(
      _bridge: PromiseOrValue<string>,
      _criteria: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<ISubsidy.SubsidyStructOutput>;

    isRegistered(_beneficiary: PromiseOrValue<string>, overrides?: CallOverrides): Promise<boolean>;

    registerBeneficiary(_beneficiary: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>;

    'setGasUsageAndMinGasPerMinute(uint256,uint32,uint32)'(
      _criteria: PromiseOrValue<BigNumberish>,
      _gasUsage: PromiseOrValue<BigNumberish>,
      _minGasPerMinute: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    'setGasUsageAndMinGasPerMinute(uint256[],uint32[],uint32[])'(
      _criteria: PromiseOrValue<BigNumberish>[],
      _gasUsage: PromiseOrValue<BigNumberish>[],
      _minGasPerMinute: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides,
    ): Promise<void>;

    subsidize(
      _bridge: PromiseOrValue<string>,
      _criteria: PromiseOrValue<BigNumberish>,
      _gasPerMinute: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    topUp(
      _bridge: PromiseOrValue<string>,
      _criteria: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    withdraw(_beneficiary: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    MIN_SUBSIDY_VALUE(overrides?: CallOverrides): Promise<BigNumber>;

    claimSubsidy(
      _criteria: PromiseOrValue<BigNumberish>,
      _beneficiary: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    claimableAmount(_beneficiary: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    getAccumulatedSubsidyAmount(
      _bridge: PromiseOrValue<string>,
      _criteria: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    getSubsidy(
      _bridge: PromiseOrValue<string>,
      _criteria: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    isRegistered(_beneficiary: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    registerBeneficiary(
      _beneficiary: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    'setGasUsageAndMinGasPerMinute(uint256,uint32,uint32)'(
      _criteria: PromiseOrValue<BigNumberish>,
      _gasUsage: PromiseOrValue<BigNumberish>,
      _minGasPerMinute: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    'setGasUsageAndMinGasPerMinute(uint256[],uint32[],uint32[])'(
      _criteria: PromiseOrValue<BigNumberish>[],
      _gasUsage: PromiseOrValue<BigNumberish>[],
      _minGasPerMinute: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    subsidize(
      _bridge: PromiseOrValue<string>,
      _criteria: PromiseOrValue<BigNumberish>,
      _gasPerMinute: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    topUp(
      _bridge: PromiseOrValue<string>,
      _criteria: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    withdraw(
      _beneficiary: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MIN_SUBSIDY_VALUE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claimSubsidy(
      _criteria: PromiseOrValue<BigNumberish>,
      _beneficiary: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    claimableAmount(_beneficiary: PromiseOrValue<string>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAccumulatedSubsidyAmount(
      _bridge: PromiseOrValue<string>,
      _criteria: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    getSubsidy(
      _bridge: PromiseOrValue<string>,
      _criteria: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    isRegistered(_beneficiary: PromiseOrValue<string>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerBeneficiary(
      _beneficiary: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    'setGasUsageAndMinGasPerMinute(uint256,uint32,uint32)'(
      _criteria: PromiseOrValue<BigNumberish>,
      _gasUsage: PromiseOrValue<BigNumberish>,
      _minGasPerMinute: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    'setGasUsageAndMinGasPerMinute(uint256[],uint32[],uint32[])'(
      _criteria: PromiseOrValue<BigNumberish>[],
      _gasUsage: PromiseOrValue<BigNumberish>[],
      _minGasPerMinute: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    subsidize(
      _bridge: PromiseOrValue<string>,
      _criteria: PromiseOrValue<BigNumberish>,
      _gasPerMinute: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    topUp(
      _bridge: PromiseOrValue<string>,
      _criteria: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    withdraw(
      _beneficiary: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;
  };
}
