/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from './common.js';

export interface IYearnRegistryInterface extends utils.Interface {
  functions: {
    'latestVault(address)': FunctionFragment;
    'numTokens()': FunctionFragment;
    'numVaults(address)': FunctionFragment;
    'tokens(uint256)': FunctionFragment;
    'vaults(address,uint256)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: 'latestVault' | 'numTokens' | 'numVaults' | 'tokens' | 'vaults',
  ): FunctionFragment;

  encodeFunctionData(functionFragment: 'latestVault', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(functionFragment: 'numTokens', values?: undefined): string;
  encodeFunctionData(functionFragment: 'numVaults', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(functionFragment: 'tokens', values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(
    functionFragment: 'vaults',
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>],
  ): string;

  decodeFunctionResult(functionFragment: 'latestVault', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'numTokens', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'numVaults', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'tokens', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'vaults', data: BytesLike): Result;

  events: {};
}

export interface IYearnRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IYearnRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    latestVault(token: PromiseOrValue<string>, overrides?: CallOverrides): Promise<[string]>;

    numTokens(overrides?: CallOverrides): Promise<[BigNumber]>;

    numVaults(token: PromiseOrValue<string>, overrides?: CallOverrides): Promise<[BigNumber]>;

    tokens(index: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<[string]>;

    vaults(
      token: PromiseOrValue<string>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<[string]>;
  };

  latestVault(token: PromiseOrValue<string>, overrides?: CallOverrides): Promise<string>;

  numTokens(overrides?: CallOverrides): Promise<BigNumber>;

  numVaults(token: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

  tokens(index: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<string>;

  vaults(
    token: PromiseOrValue<string>,
    index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides,
  ): Promise<string>;

  callStatic: {
    latestVault(token: PromiseOrValue<string>, overrides?: CallOverrides): Promise<string>;

    numTokens(overrides?: CallOverrides): Promise<BigNumber>;

    numVaults(token: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    tokens(index: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<string>;

    vaults(
      token: PromiseOrValue<string>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    latestVault(token: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    numTokens(overrides?: CallOverrides): Promise<BigNumber>;

    numVaults(token: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    tokens(index: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    vaults(
      token: PromiseOrValue<string>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    latestVault(token: PromiseOrValue<string>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    numTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    numVaults(token: PromiseOrValue<string>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokens(index: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    vaults(
      token: PromiseOrValue<string>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;
  };
}
