#!/bin/bash
set -e

# Wait for host
while ! nc -z $CONTRACTS_HOST $CONTRACTS_PORT; do sleep 1; done;

# Write to addresses.json
curl $CONTRACTS_HOST:$CONTRACTS_PORT > addresses.json

# Export keys to env variables
for KEY in ROLLUP_CONTRACT_ADDRESS FAUCET_CONTRACT_ADDRESS PERMIT_HELPER_CONTRACT_ADDRESS FEE_DISTRIBUTOR_ADDRESS GAS_PRICE_FEED_CONTRACT_ADDRESS DAI_PRICE_FEED_CONTRACT_ADDRESS BRIDGE_DATA_PROVIDER_CONTRACT_ADDRESS; do
    VALUE=$(jq -r .$KEY addresses.json)
    echo "$KEY=$VALUE"
    export $KEY=$VALUE
done
export PRICE_FEED_CONTRACT_ADDRESSES="$GAS_PRICE_FEED_CONTRACT_ADDRESS,$DAI_PRICE_FEED_CONTRACT_ADDRESS"