#!/bin/bash
# Push the PROJECTS to the given PUSH_REGISTRY with the given PUSH_LABEL.

set -e

TARGET_PROJECT=$1
ONLY_TARGET=$2
PUSH_REGISTRY=${3:-aztecprotocol}
PUSH_LABEL=${4:-latest}

PROJECTS=(
  contracts
  halloumi
  falafel
  kebab
  hummus
  end-to-end
)

# If we're calling this script from within a project directory, that's the target project.
if [ -z "$TARGET_PROJECT" ]; then
  TARGET_PROJECT=$(git rev-parse --show-prefix)
  if [ -n "$TARGET_PROJECT" ]; then
    # We are in a project folder.
    ONLY_TARGET=${ONLY_TARGET:-true}
    TARGET_PROJECT=$(basename $TARGET_PROJECT)
    cd $(git rev-parse --show-cdup)
  fi
fi

for PROJECT in ${PROJECTS[@]}; do
  if [ "$ONLY_TARGET" == "true" -a ! "$PROJECT" = "$TARGET_PROJECT" ]; then
    continue
  fi

  docker tag aztecprotocol/$PROJECT:latest $PUSH_REGISTRY/$PROJECT:$PUSH_LABEL
  echo "Pushing $PUSH_REGISTRY/$PROJECT:$PUSH_LABEL..."
  docker push $PUSH_REGISTRY/$PROJECT:$PUSH_LABEL

  if [ "$PROJECT" = "$TARGET_PROJECT" ]; then
    break
  fi
done
